backendzenteno/applications/meals/urls.py
from django.urls import path
from . import views

app_name = "meals_app"

urlpatterns = [
    # CRUD urls meal
    path(
        'meals/meal', 
        views.MealListView.as_view(),
        name='meal-list',
    ),
    path(
        'meals/meal_create', 
        views.MealCreateView.as_view(),
        name='meal-create',
    ),
    path(
        'meals/meal_edit/<pk>', 
        views.MealUpdateView.as_view(),
        name='meal-edit',
    ),
    path(
        'meals/meal_delete/<pk>', 
        views.MealDeleteView.as_view(),
        name='meal-delete',
    ),
    # CRUD urls course
    path(
        'meals/course', 
        views.CourseListView.as_view(),
        name='course-list',
    ),
    path(
        'meals/course_create', 
        views.CourseCreateView.as_view(),
        name='course-create',
    ),
    path(
        'meals/course_edit/<pk>', 
        views.CourseUpdateView.as_view(),
        name='course-edit',
    ),
    path(
        'meals/course_delete/<pk>', 
        views.CourseDeleteView.as_view(),
        name='course-delete',
    ),
]

backendzenteno/backendzenteno/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.menus.urls')),
    re_path('', include('applications.meals.urls')),
    re_path('', include('applications.apirest.urls')),
]

backendzenteno/applications/meals/models.py
from django.db import models
from model_utils.models import TimeStampedModel

from .managers import MealManager, CourseManager

# Create your models here.
class Course(TimeStampedModel):
    # Constants
    ENTRADA = 'EN'
    PLATO_PRINCIPAL = 'PP'
    POSTRE = 'PO'
    COURSE_TYPE_CHOICE = [
        (ENTRADA, 'Entrada'),
        (PLATO_PRINCIPAL, 'Plato principal'),
        (POSTRE, 'Postre'),
    ]

    # Fields
    course_name = models.CharField(max_length=50)
    course_type = models.CharField(
        max_length=2,
        choices=COURSE_TYPE_CHOICE
    )

    # Manager
    objects = CourseManager()

    #Meta
    class Meta:
        unique_together = ['course_name', 'course_type']

    # Standard methods
    def __str__(self):
        return self.course_name

class Meal(TimeStampedModel):
    # Constants
    # Fields
    meal_courses = models.ManyToManyField(Course)

    # Manager
    objects = MealManager()

    # Standard methods
    def __str__(self):
        meal_courses = ", ".join(str(courses) for courses in self.meal_courses.all())
        return "{}: {}".format(self.id ,meal_courses)

backendzenteno/applications/meals/forms.py
from django import forms
from django.contrib.auth import authenticate

from .models import Meal, Course

class MealForm(forms.Form):
    """ Formulario de registro de un almuerzo """
    entrada = forms.ModelChoiceField(
        queryset=Course.objects.filter_by_type('EN'),
        required=True,
    )

    primer_plato = forms.ModelChoiceField(
        queryset=Course.objects.filter_by_type('PP'),
        required=True,
    )

    postre = forms.ModelChoiceField(
        queryset=Course.objects.filter_by_type('PO'),
        required=True,
    )

    class Meta:
        model = Course
        fields = (
            'entrada', 
            'primer_plato', 
            'postre'
        )

    def clean_entrada(self):
        model_ids = Course.objects.filter_by_type('EN').values_list('id', flat=True)
        data_id = Course.objects.get(course_name=self.cleaned_data['entrada']).id
        if data_id not in model_ids:
            self.add_error('entrada', 'Debe seleccionar una entrada válida.')
        return self.cleaned_data['entrada']

    def clean_primer_plato(self):
        model_ids = Course.objects.filter_by_type('PP').values_list('id', flat=True)
        data_id = Course.objects.get(course_name=self.cleaned_data['primer_plato']).id
        if data_id not in model_ids:
            self.add_error('primer_plato', 'Debe seleccionar un primer plato válido.')
        return self.cleaned_data['primer_plato']

    def clean_postre(self):
        model_ids = Course.objects.filter_by_type('PO').values_list('id', flat=True)
        data_id = Course.objects.get(course_name=self.cleaned_data['postre']).id
        if data_id not in model_ids:
            self.add_error('postre', 'Debe seleccionar un postre válido.')
        return self.cleaned_data['postre']


class UpdateMealForm(forms.ModelForm, MealForm):
    """ Formulario de editar de un almuerzo """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        mealInstance = kwargs['instance']
        # Set edit instance initial values
        self.fields['entrada'].initial = mealInstance.meal_courses.all()[2]
        self.fields['primer_plato'].initial = mealInstance.meal_courses.all()[1]
        self.fields['postre'].initial = mealInstance.meal_courses.all()[0]

backendzenteno/applications/meals/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from django.views.generic.edit import FormView

from .models import Meal, Course

from .forms import (
    MealForm,
    UpdateMealForm
)

# Create your views here.
# CRUD views meal
class MealListView(LoginRequiredMixin, ListView):
    """ Listar todos los almuerzos """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/meal.html'
    context_object_name = 'meal_list'

    def get_queryset(self):
        return Meal.objects.all()
    
class MealCreateView(LoginRequiredMixin, FormView):
    """ Crear un almuerzo """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/meal_create.html'
    form_class = MealForm
    
    success_url = reverse_lazy('meals_app:meal-list')
    

    def form_valid(self, form):
        #
        meal = Meal()
        meal.save()
        
        entrada = Course.objects.get(course_name=form.cleaned_data['entrada'])
        primer_plato = Course.objects.get(course_name=form.cleaned_data['primer_plato'])
        postre = Course.objects.get(course_name=form.cleaned_data['postre'])
        meal.meal_courses.add(entrada, primer_plato, postre)

        return super(MealCreateView, self).form_valid(form)

class MealUpdateView(LoginRequiredMixin, UpdateView):
    """ Editar un almuerzo """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/meal_edit.html'
    model = Meal
    form_class = UpdateMealForm
    success_url = reverse_lazy('meals_app:meal-list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Encontrar la instancia
        meal = Meal.objects.get(id = self.kwargs['pk'])
        # Limpiar todas las many to many de esta instancia
        meal.meal_courses.clear()
        # Buscar los nuevos platos
        entrada = Course.objects.get(course_name=form.cleaned_data['entrada'])
        primer_plato = Course.objects.get(course_name=form.cleaned_data['primer_plato'])
        postre = Course.objects.get(course_name=form.cleaned_data['postre'])
        # Agregar los nuevos platos
        meal.meal_courses.add(entrada, primer_plato, postre)
        return super().form_valid(form)

class MealDeleteView(LoginRequiredMixin, DeleteView):
    """ Borrar un almuerzo """
    login_url = reverse_lazy('users_app:user-login')
    model = Meal
    success_url = reverse_lazy('meals_app:meal-list')

# CRUD views course
class CourseListView(LoginRequiredMixin, ListView):
    """ Listar todos los platos """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/course.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        return Course.objects.all()

class CourseCreateView(LoginRequiredMixin, CreateView):
    """ Crear un plato """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/course_create.html'
    model = Course
    fields = '__all__'
    success_url = reverse_lazy('meals_app:course-list')


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    """ Editar un plato """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'meals/course_edit.html'
    model = Course
    fields = '__all__'
    success_url = reverse_lazy('meals_app:course-list')


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    """ Borrar un plato """
    login_url = reverse_lazy('users_app:user-login')
    model = Course
    success_url = reverse_lazy('meals_app:course-list')

backendzenteno/templates/meals/course.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Lista de platos
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Lista de platos disponibles</h5>

<div class="row justify-content-center">
    <div class="col-auto">
        <div class="table-responsive">
            <table id="tablaCourses" class="table table-hover w-auto text-nowrap btTable" data-show-export="true"
                data-pagination="true" data-click-to-select="true" data-show-columns="true" data-sortable="true"
                data-search="true" data-live-search="true" data-buttons-align="left" data-search-align="right"
                data-server-sort="false">
                <thead>
                    <tr>
                        <th scope="col" data-field="courseID" data-sortable="true">ID</th>
                        <th scope="col" data-field="courseNombre" data-sortable="true">Nombre</th>
                        <th scope="col" data-field="courseTipo" data-sortable="true">Tipo</th>

                        <th scope="col" data-field="Accion" data-sortable="true">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for course in course_list %}
                    <tr>
                        <td>{{ course.id }}</td>
                        <td>{{ course.course_name }}</td>
                        <td>{{ course.get_course_type_display }}</td>
                        
                        <td>
                            <a class="btn btn-primary" href="{% url 'meals_app:course-edit' course.id %}"
                            role="button">Editar</a>

                            <form style="display: inline-block;" action="{% url 'meals_app:course-delete' course.id %}"
                                method="post">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                            </form>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<script src="{% static 'js/components/initBTtables.js' %}"></script>
<script src="{% static 'js/components/checkDeleteSubmit.js' %}"></script>
{% endblock subcontent %}

backendzenteno/templates/meals/course_create.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Crear plato
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Formulario para crear plato</h5>

<form method="POST">
    {% csrf_token %}

    <div class="form-group row">
        <label for="course_name" class="col-md-4 col-form-label text-md-right">Nombre del plato</label>

        <div class="col-md-6">
            {{ form.course_name  }}
        </div>
    </div>

    <div class="form-group row">
        <label for="course_type" class="col-md-4 col-form-label text-md-right">Tipo de plato</label>

        <div class="col-md-6">
            {{ form.course_type }}
        </div>
    </div>


    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Crear
            </button>

        </div>
    </div>
</form>


{% endblock subcontent %}

backendzenteno/templates/meals/course_edit.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Crear plato
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Formulario para editar plato <strong>{{ course.course_name  }}</strong></h5>

<form method="POST">
    {% csrf_token %}

    <div class="form-group row">
        <label for="course_name" class="col-md-4 col-form-label text-md-right">Nombre del plato</label>

        <div class="col-md-6">
            {{ form.course_name  }}
        </div>
    </div>

    <div class="form-group row">
        <label for="course_type" class="col-md-4 col-form-label text-md-right">Tipo de plato</label>

        <div class="col-md-6">
            {{ form.course_type }}
        </div>
    </div>


    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Editar
            </button>

        </div>
    </div>
</form>


{% endblock subcontent %}

backendzenteno/templates/meals/meal.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Lista de almuerzos
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Lista de almuerzos disponibles</h5>

<div class="row justify-content-center">
    <div class="col-auto">
        <div class="table-responsive">
            <table id="tablaMeals" class="table table-hover w-auto text-nowrap btTable" data-show-export="true"
                data-pagination="true" data-click-to-select="true" data-show-columns="true" data-sortable="true"
                data-search="true" data-live-search="true" data-buttons-align="left" data-search-align="right"
                data-server-sort="false">
                <thead>
                    <tr>
                        <th scope="col" data-field="mealID" data-sortable="true">ID</th>
                        <th scope="col" data-field="mealNombre" data-sortable="true">Nombre</th>

                        <th scope="col" data-field="Accion" data-sortable="true">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for meal in meal_list %}
                    <tr>
                        <td>{{ meal.id }}</td>
                        <td>
                            {% for course_value in meal.meal_courses.all %}
                            - {{course_value}}
                            {% endfor %}
                        </td>
                        
                        <td>
                            <a class="btn btn-primary" href="{% url 'meals_app:meal-edit' meal.id %}"
                            role="button">Editar</a>

                            <form style="display: inline-block;" action="{% url 'meals_app:meal-delete' meal.id %}"
                                method="post">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                            </form>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<script src="{% static 'js/components/initBTtables.js' %}"></script>
<script src="{% static 'js/components/checkDeleteSubmit.js' %}"></script>
{% endblock subcontent %}

backendzenteno/templates/meals/meal_create.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Crear plato
{% endblock title %}

{% block subcontent %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<h5 class="card-title mb-4">Formulario para crear un almuerzo de 3 platos</h5>
<div class="alert alert-info" role="alert">
    Un almuerzo obligatoriamente siempre llevará 3 platos.
</div>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row">
        <label for="entrada" class="col-md-4 col-form-label text-md-right">Entrada</label>

        <div class="col-md-6">
            {{ form.entrada }}
        </div>
    </div>

    <div class="form-group row">
        <label for="primer_plato" class="col-md-4 col-form-label text-md-right">Primer plato</label>

        <div class="col-md-6">
            {{ form.primer_plato }}
        </div>
    </div>

    <div class="form-group row">
        <label for="postre" class="col-md-4 col-form-label text-md-right">Postre</label>

        <div class="col-md-6">
            {{ form.postre }}
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Crear
            </button>
        </div>
    </div>
</form>

{% endblock subcontent %}

backendzenteno/templates/meals/meal_edit.html
{% extends "meals/meals_base.html" %}
{% load static %}

{% block title %}
Crear plato
{% endblock title %}

{% block subcontent %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<h5 class="card-title mb-4">Formulario para editar un almuerzo de 3 platos</h5>
<div class="alert alert-info" role="alert">
    Un almuerzo obligatoriamente siempre llevará 3 platos.
</div>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row">
        <label for="entrada" class="col-md-4 col-form-label text-md-right">Entrada</label>

        <div class="col-md-6">
            {{ form.entrada }}
        </div>
    </div>

    <div class="form-group row">
        <label for="primer_plato" class="col-md-4 col-form-label text-md-right">Primer plato</label>

        <div class="col-md-6">
            {{ form.primer_plato }}
        </div>
    </div>

    <div class="form-group row">
        <label for="postre" class="col-md-4 col-form-label text-md-right">Postre</label>

        <div class="col-md-6">
            {{ form.postre }}
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Editar
            </button>
        </div>
    </div>
</form>

{% endblock subcontent %}

backendzenteno/templates/meals/meals_base.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card shadow">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link {% if '/meals/meal' == request.path %} active {% endif %}" 
                            href="{% url 'meals_app:meal-list' %}">Lista de almuerzos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/meals/meal_create' == request.path %} active {% endif %}" " 
                            href="{% url 'meals_app:meal-create' %}">Crear almuerzo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/meals/course' == request.path %} active {% endif %}" 
                            href="{% url 'meals_app:course-list' %}">Lista de platos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/meals/course_create' == request.path %} active {% endif %}" 
                            href="{% url 'meals_app:course-create' %}">Crear plato</a>
                        </li>
                    </ul>
                </div>

                <div class="card-body py-3 my-3">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                {% block subcontent %}
                                {% endblock subcontent %}
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}