backendzenteno/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexView.as_view(), name='home'),
]

backendzenteno/backendzenteno/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.menus.urls')),
    re_path('', include('applications.meals.urls')),
    re_path('', include('applications.apirest.urls')),
]

backendzenteno/applications/home/models.py
from django.db import models

# Create your models here.

backendzenteno/applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.urls import reverse

from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from .managers import UserManager

import uuid

# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):
	# Constants
	USER_ROLE_CHOICE = (
      	(1, 'Empleado'),
      	(2, 'Manager de almuerzos'),
    )
	USERNAME_FIELD = 'user_email'

    # Fields
	user_name = models.CharField(max_length=50)
	user_email = models.EmailField(unique=True, max_length=50)
	user_role = models.PositiveSmallIntegerField(choices=USER_ROLE_CHOICE)
	user_uuid = models.UUIDField(default=uuid.uuid4, editable=False) 

	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)

	# Manager
	objects = UserManager()

	# Standard methods
	def __str__(self):
		return self.user_name + self.user_email

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
	if created:
		Token.objects.create(user=instance)

backendzenteno/applications/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class indexView(TemplateView):
    template_name = 'home/index.html'

backendzenteno/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Sistema de Almuerzos
{% endblock title %}

{% block content %}

<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-8">

          <div class="card shadow">
              <div class="card-header">
                Bienvenido a la aplicación
              </div>

              <div class="card-body py-3 my-3">
                  <div class="container-fluid">
                      <div class="row">
                          <div class="col-12">
                            <p>Usuario: <strong>{{user.user_name}}</strong></p>
                            <br>
                            <p>Rol: <strong>{{user.get_user_role_display}}</strong></p> 
                          </div>
                      </div>
                  </div>


              </div>
          </div>

      </div>
  </div>
</div>

{% endblock content %}