backendzenteno/applications/menus/urls.py
from django.urls import path
from . import views

app_name = "menus_app"

urlpatterns = [
    # CRUD urls menu
    path(
        'menus/menu', 
        views.MenuListView.as_view(),
        name='menu-list',
    ),
    path(
        'menus/menu_create', 
        views.MenuCreateView.as_view(),
        name='menu-create',
    ),
    path(
        'menus/menu_edit/<pk>', 
        views.MenuUpdateView.as_view(),
        name='menu-edit',
    ),
    path(
        'menus/menu_delete/<pk>', 
        views.MenuDeleteView.as_view(),
        name='menu-delete',
    ),
    path(
        'menus/menu_detail/<pk>', 
        views.MenuDetailView.as_view(),
        name='menu-detail',
    ),
    path(
        'menus/select_menu/<uuid:user_uuid>', 
        views.SelectMenuView.as_view(),
        name='select-menu',
    ),
    path(
        'menus/my_menu_meals/<pk>', 
        views.MyMenuMealsView.as_view(),
        name='my-menu-meals',
    ),
    path(
        'menus/menu_list_selections', 
        views.MenuMealsListView.as_view(),
        name='menu-list-selections',
    ),

]

backendzenteno/backendzenteno/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.menus.urls')),
    re_path('', include('applications.meals.urls')),
    re_path('', include('applications.apirest.urls')),
]

backendzenteno/applications/menus/models.py
from django.db import models
from model_utils.models import TimeStampedModel

from .managers import MenuManager, Menu_mealManager, Menu_meal_userManager

from ..meals.models import Meal
from ..users.models import User

# Create your models here.
class Menu(TimeStampedModel):
    # Constants
    # Fields
    menu_date = models.DateField()
    menu_meals = models.ManyToManyField(Meal, through='Menu_meal')

    # Manager
    objects = MenuManager()

    # Standard methods
    def __str__(self):
	    return str(self.menu_date)

class Menu_meal(TimeStampedModel):
    # Constants
    # Fields
    menu_id = models.ForeignKey(Menu, on_delete=models.CASCADE)
    meal_id = models.ForeignKey(Meal, on_delete=models.CASCADE)

    # Manager
    objects = Menu_mealManager()

    # Standard methods
    def __str__(self):
	    return str(self.menu_id) + str(self.meal_id)

class Menu_meal_user(TimeStampedModel):
    # Constants
    # Fields
    menu_meal_id = models.ForeignKey(Menu_meal, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    commentary = models.TextField(blank=True)

    # Manager
    objects = Menu_meal_userManager()

    # Meta
    class Meta:
        unique_together = ['menu_meal_id', 'user_id']

    # Standard methods
    def __str__(self):
	    return str(self.menu_meal_id) + str(self.user_id)

backendzenteno/applications/menus/forms.py
import datetime
from datetime import date

from django import forms
from django.contrib.auth import authenticate

from .models import Menu
from ..meals.models import Meal

class MenuForm(forms.Form):
    """ Formulario de registro de un almuerzo """
    menu_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            }
        ),
        required=True
    )


    menu_meals = forms.ModelMultipleChoiceField(
        queryset=Meal.objects.all(),
        required=True,
    )

    class Meta:
        model = Meal
        fields = (
            'menu_date', 
            'menu_meals', 
        )


    def clean_menu_date(self):
        form_date = self.cleaned_data['menu_date']
        if self.is_menu_to_past(form_date):
            self.add_error('menu_date', 'No se pueden crear menú para hoy o el pasado.')

        # Check si esta fecha ya tiene almuerzos
        if (Menu.objects.date_exists(form_date)):
            self.add_error('menu_date', 'Esta fecha ya tiene un menú.')

        return form_date


    def clean_menu_meals(self):
        form_meals = self.cleaned_data['menu_meals']
        meal_ids = self.get_ids_from_meals(form_meals)
        meal_model_ids = Meal.objects.all().values_list('id', flat=True)
        # Si estos almuerzos no existen en los almuerzos (tweaking de values en form)
        for meal_id in meal_ids:
            if meal_id not in meal_model_ids:
                self.add_error('menu_meals', 'Debe seleccionar un almuerzo válido.')
        return form_meals

    def get_ids_from_meals(self, meals):
        meal_ids = []
        for meal in meals:
            meal_ids.append(meal.id)
        return meal_ids

    # No se pueden crear menus hacia el pasado
    def is_menu_to_past(self, date):
        today = date.today()
        if date < today:
            return True
        return False


class MenuEditForm(forms.ModelForm, MenuForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        modelInstance = Menu.objects.get(menu_date = str(kwargs['instance']))
        # Set edit instance initial values
        self.fields['menu_date'].initial = kwargs['instance']
        self.fields['menu_meals'].initial = modelInstance.menu_meals.all()

    # Override de clean fecha de MenuForm
    def clean_menu_date(self):
        form_date = self.cleaned_data['menu_date']
        if self.is_menu_to_past(form_date):
            self.add_error('menu_date', 'No se puede editar este menú para hoy o el pasado.')

        initial_date = self.fields['menu_date'].initial
        # Si esta fecha es distinta que la inicial
        if not str(form_date) == str(initial_date):
            # Chequear que esta nueva fecha no tiene un menú
            if (Menu.objects.date_exists(form_date)):
                self.add_error('menu_date', 'Esta fecha ya tiene un menú.')

        return form_date

    
class SelectMenuForm(forms.Form):
    """ Formulario de selección de almuerzo del menú disponible """
    # Seleccionar almuerzo y un comentario opcional
    meals = forms.ModelChoiceField(
        queryset=None,
        required=True,
    )

    menu = forms.IntegerField()

    
    commentary = forms.CharField(
        max_length=300, 
        widget=forms.TextInput(
            attrs={
                'size':'40'
            }
        ),
        required=False
    )

    class Meta:
        fields = (
            'meals',
            'menu', 
            'commentary', 
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        today = date.today()
        modelInstance = Menu.objects.get(menu_date = str(today))

        now = datetime.datetime.now()
        # Restricción de tiempo
        if (now.hour >= 11):
            self.fields['meals'].disabled = True
            self.fields['menu'].disabled = True
            self.fields['commentary'].disabled = True

        # menu_meals Queryset
        self.fields['meals'].queryset = modelInstance.menu_meals.all()
        self.fields['menu'].initial = modelInstance.id

    def clean_meals(self):
        if self.is_expired:
            self.add_error('meals', 'La selección ha expirado.')

        meal = self.cleaned_data['meals']
        today = date.today()

        is_valid = Menu.objects.is_valid_meal_for_today(meal.id, today)
        if is_valid:
            return meal
        else:
            self.add_error('meals', 'Seleccione un almuerzo válido.')

    def clean_commentary(self):
        if self.is_expired:
            self.add_error('commentary', 'La selección ha expirado.')

        commentary = self.cleaned_data['commentary']
        if len(commentary) > 300:
            self.add_error('commentary', 'Su comentario ha superado el límite.')
        elif len(commentary) == 0:
            return ''
        else:
            return commentary

    def is_expired(self):
        now = datetime.datetime.now()
        # Restricción de tiempo
        if (now.hour >= 11):
            return True
        return False

backendzenteno/applications/menus/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from django.views.generic.edit import FormView

from .models import Menu, Menu_meal, Menu_meal_user
from ..users.models import User

from ..apirest.slackapi import SlackAPIMethods


from .forms import (
    MenuForm,
    MenuEditForm,
    SelectMenuForm
)
# Create your views here.
# CRUD views menu
class MenuListView(LoginRequiredMixin, ListView):
    """ Listar todos los menus """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu.html'
    context_object_name = 'menu_list'
    success_url = reverse_lazy('menus_app:menu-list')

    def get_queryset(self):
        return Menu.objects.all()

    def post(self, request, *args, **kwargs):
        
        slack = SlackAPIMethods()
        slack_users = slack.send_empleados_direct_message()
        
        data = Menu.objects.all()
        return render(request, self.template_name, {'menu_list': data})


class MenuCreateView(LoginRequiredMixin, FormView):
    """ Crear un menu """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_create.html'
    form_class = MenuForm
    success_url = reverse_lazy('menus_app:menu-list')

    def form_valid(self, form):
        menu = Menu(
            menu_date = form.cleaned_data['menu_date']
        )
        menu.save()
        for almuerzo in form.cleaned_data['menu_meals']:
            menu.menu_meals.add(almuerzo)

        return super(MenuCreateView, self).form_valid(form)


class MenuUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_edit.html'
    model = Menu
    form_class = MenuEditForm
    success_url = reverse_lazy('menus_app:menu-list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class MenuDeleteView(LoginRequiredMixin, DeleteView):
    """ Borrar un menu """
    login_url = reverse_lazy('users_app:user-login')
    model = Menu
    success_url = reverse_lazy('menus_app:menu-list')

class MenuDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_detail.html'
    model = Menu
    context_object_name = 'menu_detail'

class SelectMenuView(FormView):
    """ Crear una selección """
    template_name = 'menus/select_menu.html'
    form_class = SelectMenuForm
    success_url = reverse_lazy('home')
    
    def form_valid(self, form):
        user_uuid = self.kwargs['user_uuid']
        user_instance = User.objects.get(user_uuid = user_uuid)

        menu_id = form.cleaned_data['menu']
        meal = form.cleaned_data['meals']
        commentary = form.cleaned_data['commentary']
        menu_meal_instance = Menu_meal.objects.get(menu_id = menu_id, meal_id = meal.id)
        
        Menu_meal_user.objects.create(
            menu_meal_id = menu_meal_instance,
            user_id = user_instance,
            commentary = commentary
        )
        return super().form_valid(form)

class MyMenuMealsView(LoginRequiredMixin, ListView):
    """ Ver mi propia selección """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_my_meals.html'
    context_object_name = 'menu_meal_user_list'
    success_url = reverse_lazy('menus_app:my-menu-meals')

    def get_queryset(self):
        menu_meal_user = Menu_meal_user.objects.filter(user_id = self.kwargs['pk'])
        return menu_meal_user


class MenuMealsListView(LoginRequiredMixin, ListView):
    """ Ver todas las selecciones """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_list_selections.html'
    context_object_name = 'menu_meal_user_list'
    success_url = reverse_lazy('menus_app:menu-list-selections')

    def get_queryset(self):
        get_empleados = User.objects.filter(user_role = 1)
        menu_meal_user_list = []
        for empleado in get_empleados:
            menu_meal_user = Menu_meal_user.objects.filter(user_id = empleado.id)
            if menu_meal_user.exists():
                menu_meal_user_list.append(menu_meal_user)
        return menu_meal_user_list

backendzenteno/templates/menus/menu.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Lista de menus
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Lista de menús disponibles</h5>

<div class="row justify-content-center">
    <div class="col-auto">
        <div class="table-responsive">
            <table id="tablaMenus" class="table table-hover w-auto text-nowrap btTable" data-show-export="true"
                data-pagination="true" data-click-to-select="true" data-show-columns="true" data-sortable="true"
                data-search="true" data-live-search="true" data-buttons-align="left" data-search-align="right"
                data-server-sort="false">
                <thead>
                    <tr>
                        <th scope="col" data-field="menuID" data-sortable="true">ID</th>
                        <th scope="col" data-field="menuYear" data-sortable="true">Año</th>
                        <th scope="col" data-field="menuMonth" data-sortable="true">Mes</th>
                        <th scope="col" data-field="menuDay" data-sortable="true">Día</th>

                        <th scope="col" data-field="Accion" data-sortable="true">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    
                    {% for menu in menu_list %}
                    <tr>
                        <td>{{ menu.id }}</td>
                        <td>{{ menu.menu_date|date:'Y' }}</td>
                        <td>{{ menu.menu_date|date:'m' }}</td>
                        <td>{{ menu.menu_date|date:'d' }}</td>
                        
                        <td>
                            <a class="btn btn-primary" href="{% url 'menus_app:menu-detail' menu.id %}"
                            role="button">Ver detalle</a>

                            <a class="btn btn-secondary" href="{% url 'menus_app:menu-edit' menu.id %}"
                            role="button">Editar</a>

                            <form style="display: inline-block;" action="{% url 'menus_app:menu-delete' menu.id %}"
                                method="post">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                            </form>

                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="col-12">
            <form method="POST">
                {% csrf_token %}
            
                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Enviar notificaciones
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="{% static 'js/components/initBTtables.js' %}"></script>
<script src="{% static 'js/components/checkDeleteSubmit.js' %}"></script>
{% endblock subcontent %}

backendzenteno/templates/menus/menu_create.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Crear menú
{% endblock title %}

{% block subcontent %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<h5 class="card-title mb-4">Formulario para crear un menú</h5>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row">
        <label for="menu_date" class="col-md-4 col-form-label text-md-right">Fecha</label>

        <div class="col-md-6">
            {{ form.menu_date }}
        </div>
    </div>

    <div class="form-group row">
        <label for="menu_meals" class="col-md-4 col-form-label text-md-right">Elegir almuerzos</label>
            {{ form.menu_meals }}
        <div class="col-md-6">
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Crear
            </button>
        </div>
    </div>
</form>

{% endblock subcontent %}

backendzenteno/templates/menus/menu_detail.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Detalle de menú
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Detalle del menu: {{menu_detail.id}}</h5>

<div class="row justify-content-center">
    <div class="col-12">
        <p>Fecha: <strong>{{ menu_detail.menu_date }}</strong></p>

        <ul class="list-group"></ul>
        {% for meals in menu_detail.menu_meals.all %}
            <li class="list-group-item">
                {{ forloop.counter }})
                {% for courses in meals.meal_courses.all %}
                    - {{ courses }}
                {% endfor %}
            </li>
        {% endfor %}
        </ul>
                    
{% endblock subcontent %}

backendzenteno/templates/menus/menu_edit.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Editar menú
{% endblock title %}

{% block subcontent %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<h5 class="card-title mb-4">Formulario para editar un menú</h5>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row">
        <label for="menu_date" class="col-md-4 col-form-label text-md-right">Fecha</label>

        <div class="col-md-6">
            {{ form.menu_date }}
        </div>
    </div>

    <div class="form-group row">
        <label for="menu_meals" class="col-md-4 col-form-label text-md-right">Elegir almuerzos</label>
            {{ form.menu_meals }}
        <div class="col-md-6">
        </div>
    </div>

    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Editar
            </button>
        </div>
    </div>
</form>

{% endblock subcontent %}

backendzenteno/templates/menus/menu_list_selections.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Lista de menus seleccionados por usuario y fecha
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Lista de menus seleccionados por usuario y fecha</h5>
<div class="row justify-content-center">
    <div class="col-auto">
        <div class="table-responsive">
            <table id="tablaMenus" class="table table-hover w-auto text-nowrap btTable" data-show-export="true"
                data-pagination="true" data-click-to-select="true" data-show-columns="true" data-sortable="true"
                data-search="true" data-live-search="true" data-buttons-align="left" data-search-align="right"
                data-server-sort="false">
                <thead>
                    <tr>
                        <th scope="col" data-field="menuID" data-sortable="true">ID</th>
                        <th scope="col" data-field="menuUser" data-sortable="true">Usuario</th>
                        <th scope="col" data-field="menuYear" data-sortable="true">Fecha</th>
                        <th scope="col" data-field="menuMonth" data-sortable="true">Almuerzo</th>
                        <th scope="col" data-field="menuDay" data-sortable="true">Comentario</th>


                    </tr>
                </thead>
                <tbody>
                    
                    {% for menu_meal_user in menu_meal_user_list %}
                    <tr>
                        {% for objects in menu_meal_user %}
                        <td> {{ objects.id }} </td>
                        <td> {{ objects.user_id.user_email }} </td>
                        <td> {{ objects.menu_meal_id.menu_id }} </td>
                        <td> {{ objects.menu_meal_id.meal_id }} </td>
                        <td> {{ objects.commentary }} </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="{% static 'js/components/initBTtables.js' %}"></script>
{% endblock subcontent %}

backendzenteno/templates/menus/menu_my_meals.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Lista de menus
{% endblock title %}

{% block subcontent %}

<h5 class="card-title mb-4">Lista de menús seleccionados</h5>

<div class="row justify-content-center">
    <div class="col-auto">
        <div class="table-responsive">
            <table id="tablaMenus" class="table table-hover w-auto text-nowrap btTable" data-show-export="true"
                data-pagination="true" data-click-to-select="true" data-show-columns="true" data-sortable="true"
                data-search="true" data-live-search="true" data-buttons-align="left" data-search-align="right"
                data-server-sort="false">
                <thead>
                    <tr>
                        <th scope="col" data-field="menuID" data-sortable="true">ID</th>
                        <th scope="col" data-field="menuYear" data-sortable="true">Fecha</th>
                        <th scope="col" data-field="menuMonth" data-sortable="true">Almuerzo</th>
                        <th scope="col" data-field="menuDay" data-sortable="true">Comentario</th>


                    </tr>
                </thead>
                <tbody>
                    
                    {% for menu_meal_user in menu_meal_user_list %}
                    <tr>
                        <td>{{ menu_meal_user.id }}</td>
                        <td>{{ menu_meal_user.menu_meal_id.menu_id }}</td>
                        <td>{{ menu_meal_user.menu_meal_id.meal_id }}</td>
                        <td>{{ menu_meal_user.commentary }}</td>
                        
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="{% static 'js/components/initBTtables.js' %}"></script>
{% endblock subcontent %}

backendzenteno/templates/menus/menus_base.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card shadow">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        {% if user.user_role == 2 %}
                        <li class="nav-item">
                            <a class="nav-link {% if '/menus/menu' == request.path %} active {% endif %}" 
                            href="{% url 'menus_app:menu-list' %}">Lista de menús</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/menus/menu_create' == request.path %} active {% endif %}" 
                            href="{% url 'menus_app:menu-create' %}">Crear menú</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/menus/menu_list_selections' == request.path %} active {% endif %}"
                            href="{% url 'menus_app:menu-list-selections' %}">Ver menús seleccionados</a>
                        </li>
                        {% elif user.user_role == 1 %}
                        <li class="nav-item">
                            <a class="nav-link {% if '/menus/menu_my_meals/' == request.path %} active {% endif %}" 
                            href="{% url 'menus_app:my-menu-meals' user.id %}">Mis almuerzos</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

                <div class="card-body py-3 my-3">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                {% block subcontent %}
                                {% endblock subcontent %}
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

backendzenteno/templates/menus/select_menu.html
{% extends "menus/menus_base.html" %}
{% load static %}

{% block title %}
Seleccionar menú
{% endblock title %}

{% block subcontent %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

<h5 class="card-title mb-4">Seleccione el almuerzo para el menú del día.</h5>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group row">
        <label for="meals" class="col-md-4 col-form-label text-md-right">Almuerzo:</label>

        <div class="col-md-6">
            {{ form.meals }}
        </div>
    </div>

    <div class="form-group row">
        <label for="commentary" class="col-md-4 col-form-label text-md-right">Comentario (opcional):</label>
            {{ form.commentary }}
        <div class="col-md-6">
        </div>
    </div>

    {{ form.menu.as_hidden }}

    <div class="form-group row mb-0">
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Crear
            </button>
        </div>
    </div>
</form>

{% endblock subcontent %}