backendzenteno/applications/meals/urls.py
from django.urls import path
from . import views

app_name = "meals_app"

urlpatterns = [
    # CRUD urls meal
    path(
        'meals/meal', 
        views.MealListView.as_view(),
        name='meal-list',
    ),
    path(
        'meals/meal_create', 
        views.MealCreateView.as_view(),
        name='meal-create',
    ),
    path(
        'meals/meal_edit/<pk>', 
        views.MealUpdateView.as_view(),
        name='meal-edit',
    ),
    path(
        'meals/meal_delete/<pk>', 
        views.MealDeleteView.as_view(),
        name='meal-delete',
    ),
    # CRUD urls course
    path(
        'meals/course', 
        views.CourseListView.as_view(),
        name='course-list',
    ),
    path(
        'meals/course_create', 
        views.CourseCreateView.as_view(),
        name='course-create',
    ),
    path(
        'meals/course_edit/<pk>', 
        views.CourseUpdateView.as_view(),
        name='course-edit',
    ),
    path(
        'meals/course_delete/<pk>', 
        views.CourseDeleteView.as_view(),
        name='course-delete',
    ),
]

backendzenteno/applications/menus/urls.py
from django.urls import path
from . import views

app_name = "menus_app"

urlpatterns = [
    # CRUD urls menu
    path(
        'menus/menu', 
        views.MenuListView.as_view(),
        name='menu-list',
    ),
    path(
        'menus/menu_create', 
        views.MenuCreateView.as_view(),
        name='menu-create',
    ),
    path(
        'menus/menu_edit/<pk>', 
        views.MenuUpdateView.as_view(),
        name='menu-edit',
    ),
    path(
        'menus/menu_delete/<pk>', 
        views.MenuDeleteView.as_view(),
        name='menu-delete',
    ),
    path(
        'menus/menu_detail/<pk>', 
        views.MenuDetailView.as_view(),
        name='menu-detail',
    ),
    path(
        'menus/select_menu/<uuid:user_uuid>', 
        views.SelectMenuView.as_view(),
        name='select-menu',
    ),
    path(
        'menus/my_menu_meals/<pk>', 
        views.MyMenuMealsView.as_view(),
        name='my-menu-meals',
    ),
    path(
        'menus/menu_list_selections', 
        views.MenuMealsListView.as_view(),
        name='menu-list-selections',
    ),

]

backendzenteno/applications/users/urls.py
from django.urls import path
from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'users/register', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'users/login', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'users/logout', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'users/profile/<pk>', 
        views.UserUpdateView.as_view(),
        name='user-profile',
    ),
]

backendzenteno/backendzenteno/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.menus.urls')),
    re_path('', include('applications.meals.urls')),
    re_path('', include('applications.apirest.urls')),
]

backendzenteno/applications/menus/models.py
from django.db import models
from model_utils.models import TimeStampedModel

from .managers import MenuManager, Menu_mealManager, Menu_meal_userManager

from ..meals.models import Meal
from ..users.models import User

# Create your models here.
class Menu(TimeStampedModel):
    # Constants
    # Fields
    menu_date = models.DateField()
    menu_meals = models.ManyToManyField(Meal, through='Menu_meal')

    # Manager
    objects = MenuManager()

    # Standard methods
    def __str__(self):
	    return str(self.menu_date)

class Menu_meal(TimeStampedModel):
    # Constants
    # Fields
    menu_id = models.ForeignKey(Menu, on_delete=models.CASCADE)
    meal_id = models.ForeignKey(Meal, on_delete=models.CASCADE)

    # Manager
    objects = Menu_mealManager()

    # Standard methods
    def __str__(self):
	    return str(self.menu_id) + str(self.meal_id)

class Menu_meal_user(TimeStampedModel):
    # Constants
    # Fields
    menu_meal_id = models.ForeignKey(Menu_meal, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    commentary = models.TextField(blank=True)

    # Manager
    objects = Menu_meal_userManager()

    # Meta
    class Meta:
        unique_together = ['menu_meal_id', 'user_id']

    # Standard methods
    def __str__(self):
	    return str(self.menu_meal_id) + str(self.user_id)

backendzenteno/applications/menus/forms.py
import datetime
from datetime import date

from django import forms
from django.contrib.auth import authenticate

from .models import Menu
from ..meals.models import Meal

class MenuForm(forms.Form):
    """ Formulario de registro de un almuerzo """
    menu_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            }
        ),
        required=True
    )


    menu_meals = forms.ModelMultipleChoiceField(
        queryset=Meal.objects.all(),
        required=True,
    )

    class Meta:
        model = Meal
        fields = (
            'menu_date', 
            'menu_meals', 
        )


    def clean_menu_date(self):
        form_date = self.cleaned_data['menu_date']
        if self.is_menu_to_past(form_date):
            self.add_error('menu_date', 'No se pueden crear menú para hoy o el pasado.')

        # Check si esta fecha ya tiene almuerzos
        if (Menu.objects.date_exists(form_date)):
            self.add_error('menu_date', 'Esta fecha ya tiene un menú.')

        return form_date


    def clean_menu_meals(self):
        form_meals = self.cleaned_data['menu_meals']
        meal_ids = self.get_ids_from_meals(form_meals)
        meal_model_ids = Meal.objects.all().values_list('id', flat=True)
        # Si estos almuerzos no existen en los almuerzos (tweaking de values en form)
        for meal_id in meal_ids:
            if meal_id not in meal_model_ids:
                self.add_error('menu_meals', 'Debe seleccionar un almuerzo válido.')
        return form_meals

    def get_ids_from_meals(self, meals):
        meal_ids = []
        for meal in meals:
            meal_ids.append(meal.id)
        return meal_ids

    # No se pueden crear menus hacia el pasado
    def is_menu_to_past(self, date):
        today = date.today()
        if date < today:
            return True
        return False


class MenuEditForm(forms.ModelForm, MenuForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        modelInstance = Menu.objects.get(menu_date = str(kwargs['instance']))
        # Set edit instance initial values
        self.fields['menu_date'].initial = kwargs['instance']
        self.fields['menu_meals'].initial = modelInstance.menu_meals.all()

    # Override de clean fecha de MenuForm
    def clean_menu_date(self):
        form_date = self.cleaned_data['menu_date']
        if self.is_menu_to_past(form_date):
            self.add_error('menu_date', 'No se puede editar este menú para hoy o el pasado.')

        initial_date = self.fields['menu_date'].initial
        # Si esta fecha es distinta que la inicial
        if not str(form_date) == str(initial_date):
            # Chequear que esta nueva fecha no tiene un menú
            if (Menu.objects.date_exists(form_date)):
                self.add_error('menu_date', 'Esta fecha ya tiene un menú.')

        return form_date

    
class SelectMenuForm(forms.Form):
    """ Formulario de selección de almuerzo del menú disponible """
    # Seleccionar almuerzo y un comentario opcional
    meals = forms.ModelChoiceField(
        queryset=None,
        required=True,
    )

    menu = forms.IntegerField()

    
    commentary = forms.CharField(
        max_length=300, 
        widget=forms.TextInput(
            attrs={
                'size':'40'
            }
        ),
        required=False
    )

    class Meta:
        fields = (
            'meals',
            'menu', 
            'commentary', 
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        today = date.today()
        modelInstance = Menu.objects.get(menu_date = str(today))

        now = datetime.datetime.now()
        # Restricción de tiempo
        if (now.hour >= 11):
            self.fields['meals'].disabled = True
            self.fields['menu'].disabled = True
            self.fields['commentary'].disabled = True

        # menu_meals Queryset
        self.fields['meals'].queryset = modelInstance.menu_meals.all()
        self.fields['menu'].initial = modelInstance.id

    def clean_meals(self):
        if self.is_expired:
            self.add_error('meals', 'La selección ha expirado.')

        meal = self.cleaned_data['meals']
        today = date.today()

        is_valid = Menu.objects.is_valid_meal_for_today(meal.id, today)
        if is_valid:
            return meal
        else:
            self.add_error('meals', 'Seleccione un almuerzo válido.')

    def clean_commentary(self):
        if self.is_expired:
            self.add_error('commentary', 'La selección ha expirado.')

        commentary = self.cleaned_data['commentary']
        if len(commentary) > 300:
            self.add_error('commentary', 'Su comentario ha superado el límite.')
        elif len(commentary) == 0:
            return ''
        else:
            return commentary

    def is_expired(self):
        now = datetime.datetime.now()
        # Restricción de tiempo
        if (now.hour >= 11):
            return True
        return False

backendzenteno/applications/menus/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from django.views.generic.edit import FormView

from .models import Menu, Menu_meal, Menu_meal_user
from ..users.models import User

from ..apirest.slackapi import SlackAPIMethods


from .forms import (
    MenuForm,
    MenuEditForm,
    SelectMenuForm
)
# Create your views here.
# CRUD views menu
class MenuListView(LoginRequiredMixin, ListView):
    """ Listar todos los menus """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu.html'
    context_object_name = 'menu_list'
    success_url = reverse_lazy('menus_app:menu-list')

    def get_queryset(self):
        return Menu.objects.all()

    def post(self, request, *args, **kwargs):
        
        slack = SlackAPIMethods()
        slack_users = slack.send_empleados_direct_message()
        
        data = Menu.objects.all()
        return render(request, self.template_name, {'menu_list': data})


class MenuCreateView(LoginRequiredMixin, FormView):
    """ Crear un menu """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_create.html'
    form_class = MenuForm
    success_url = reverse_lazy('menus_app:menu-list')

    def form_valid(self, form):
        menu = Menu(
            menu_date = form.cleaned_data['menu_date']
        )
        menu.save()
        for almuerzo in form.cleaned_data['menu_meals']:
            menu.menu_meals.add(almuerzo)

        return super(MenuCreateView, self).form_valid(form)


class MenuUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_edit.html'
    model = Menu
    form_class = MenuEditForm
    success_url = reverse_lazy('menus_app:menu-list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class MenuDeleteView(LoginRequiredMixin, DeleteView):
    """ Borrar un menu """
    login_url = reverse_lazy('users_app:user-login')
    model = Menu
    success_url = reverse_lazy('menus_app:menu-list')

class MenuDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_detail.html'
    model = Menu
    context_object_name = 'menu_detail'

class SelectMenuView(FormView):
    """ Crear una selección """
    template_name = 'menus/select_menu.html'
    form_class = SelectMenuForm
    success_url = reverse_lazy('home')
    
    def form_valid(self, form):
        user_uuid = self.kwargs['user_uuid']
        user_instance = User.objects.get(user_uuid = user_uuid)

        menu_id = form.cleaned_data['menu']
        meal = form.cleaned_data['meals']
        commentary = form.cleaned_data['commentary']
        menu_meal_instance = Menu_meal.objects.get(menu_id = menu_id, meal_id = meal.id)
        
        Menu_meal_user.objects.create(
            menu_meal_id = menu_meal_instance,
            user_id = user_instance,
            commentary = commentary
        )
        return super().form_valid(form)

class MyMenuMealsView(LoginRequiredMixin, ListView):
    """ Ver mi propia selección """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_my_meals.html'
    context_object_name = 'menu_meal_user_list'
    success_url = reverse_lazy('menus_app:my-menu-meals')

    def get_queryset(self):
        menu_meal_user = Menu_meal_user.objects.filter(user_id = self.kwargs['pk'])
        return menu_meal_user


class MenuMealsListView(LoginRequiredMixin, ListView):
    """ Ver todas las selecciones """
    login_url = reverse_lazy('users_app:user-login')
    template_name = 'menus/menu_list_selections.html'
    context_object_name = 'menu_meal_user_list'
    success_url = reverse_lazy('menus_app:menu-list-selections')

    def get_queryset(self):
        get_empleados = User.objects.filter(user_role = 1)
        menu_meal_user_list = []
        for empleado in get_empleados:
            menu_meal_user = Menu_meal_user.objects.filter(user_id = empleado.id)
            if menu_meal_user.exists():
                menu_meal_user_list.append(menu_meal_user)
        return menu_meal_user_list

backendzenteno/templates/layout/footer.html
{% load static %}
<footer class="text-white d-flex align-items-end bg-dark mt-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-3 mt-2">
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="mb-1"><img src="{% static 'img/footer/phone.svg' %}" alt=""> Mesa de
                                    Ayuda:</p>
                                <p class="mt-0"><img src="{% static 'img/footer/chile.svg' %}" alt=""> (+56 9) 9129
                                    1640
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 mt-1 text-center">
                        <img src="{% static 'img/footer/cornershop.png' %}" alt="" style="width:150px; height:30px;">
                        <hr>
                        <p class="mt-1">© 2020 nombreempresa S.A. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-sm-3 mt-2">
                        <div class="row">
                            <div class="col-sm-6">&nbsp;</div>
                            <div class="col-sm-6">
                                <p class="mb-1"><img src="{% static 'img/footer/mail.svg' %}" alt=""> Mail de
                                    contacto:</p>
                                <p class="mt-0">izenteno22@gmail.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

backendzenteno/templates/layout/header.html
{% load static %}
<!-- CSS STYLES -->
<link rel="stylesheet" href="{% static 'css/libs/familyTitilliumWeb.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/libs/bootstrap.min.css' %}">
<!-- Font Awesome CSS -->
<link rel="stylesheet" href="{% static 'css/libs/fontAwesomeAll.css' %}">
<link rel="stylesheet" href="{% static 'css/libs/pretty-checkbox.min.css' %}">
<!-- JS -->
<!-- jQuery JS -->
<script src="{% static 'js/libs/jquery-3.4.1.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'js/libs/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/libs/bootstrap.min.js' %}"></script>
<!-- Font Awesome JS -->
<script src="{% static 'js/libs/solid.js' %}"></script>
<script src="{% static 'js/libs/fontawesome.js' %}"></script>

<!-- Bootstrap Tables-->
<link href="{% static 'css/libs/bootstrap-table.min.css' %}" rel="stylesheet">
<script src="{% static 'js/libs/bootstrap-table.min.js' %}"></script>
<!-- Bootstrap Tables Export Extension -->
<script src="{% static 'js/libs/bootstrap-table-export.min.js' %}"></script>
<!-- JS Exports plugin Bootstrap Tables-->
<script src="{% static 'js/libs/tableExport.min.js' %}"></script>
<script src="{% static 'js/libs/jspdf.min.js' %}"></script>
<script src="{% static 'js/libs/jspdf.plugin.autotable.js' %}"></script>

backendzenteno/templates/layout/menu.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-white shadow d-flex align-items-start">
    <div class="container-fluid">
        <ul class="navbar-nav mr-auto text-center">
            <a class="navbar-brand">
                Sistema de almuerzos
            </a>
        </ul>
        <ul class="navbar-nav m-auto text-center">

            {% if not user.is_anonymous %}
            <!-- Estoy logeado -->
            <li class="nav-item mx-2">
                <a class="nav-link" href="">
                    <span style="font-size: 1.5em;">
                        <i class="fas fa-home"></i>
                    </span><br>
                    Home
                </a>
            </li>

            <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'menus_app:menu-list' %}">
                    <span style="font-size: 1.5em;">
                        <i class="fas fa-clipboard-list"></i>
                    </span><br>
                    Menus
                </a>
            </li>

            {% if user.user_role == 2 %}
            <li class="nav-item mx-2">
                <a class="nav-link" href="{% url 'meals_app:meal-list' %}">
                    <span style="font-size: 1.5em;">
                        <i class="fas fa-utensils"></i>
                    </span><br>
                    Almuerzos
                </a>
            </li>
            {% endif %}
            {% endif %}
        </ul>

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            {% if not user.is_anonymous %}
            <!-- Estoy logeado -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users_app:user-profile' user.id %}">Mi perfil <i class="fas fa-user"></i></a>
            </li>
            <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'users_app:user-logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <!-- No estoy logeado -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users_app:user-login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
            </li>
            <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'users_app:user-register' %}">Registrar <i class="fas fa-user-plus"></i></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>